apiVersion: v1
kind: Pod
metadata:
  name: santi-nginx
  labels:
    app: santi-nginx
spec:
  containers:
    - name: container-pod-nginx
      image: nginx:latest
      ports:
        - containerPort: 8080


# apiVersion: v1
# kind: Pod
# metadata:
#   name: santi-nodejs
#   labels:
#     app: santi-nodejs
# spec:
#   containers:
#     - name: container-pod-cube
#       image: alsysew/validador-cpf-java:v1.0.1
#       ports:
#         - containerPort: 3000


# kubectl apply -f pod-nginx.yml
# kubectl describe -f pod-nginx.yml
# kubectl delete -f pod-nginx.yml
