apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: java-replicaset
spec:
  template: 
    metadata:
      name: santi-nodejs
      labels:
        app: santi-nodejs
    spec:
      containers:
        - name: container-pod-cube
          image: alsysew/validador-cpf-java:v1.0.1
          ports:
            - containerPort: 3000

  replicas: 3
  selector:
    matchLabels:
      app: pod-notejs-replicaset


# $ kubectl logs -l app=lable-pod-java # log de todos os lables do replicaset
# $ kubectl logs --tail=20 --follow=true -l app=lable-pod-java